# Generated by Django 5.1.7 on 2025-04-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_test_is_active_studenttest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttest',
            old_name='awnsers',
            new_name='answers',
        ),
    ]
