# Generated by Django 5.1.7 on 2025-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_studenttest_answers_alter_studenttest_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
