# Generated by Django 5.1.7 on 2025-07-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_test_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backend.studenttest'),
        ),
    ]
