# Generated by Django 5.1.7 on 2025-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_studentanswer_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
