# Generated by Django 5.1.7 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=20),
            preserve_default=False,
        ),
    ]
