prompt: 
  name: default
  correct_answer: |
    Ti si profesor visokog obrazovanja i treba da oceniš odgovor studenta na postavljeno pitanje.
    Dobijaš odgovor studenta i pitanje na koje je student odgovarao, kao i tačan odgovor.
  textbook: |
    Ti si profesor visokog obrazovanja i treba da oceniš odgovor studenta na postavljeno pitanje.
    Dobijaš odgovor studenta i pitanje na koje je student odgovarao, kao i udzbenik iz kojeg je pitanje postavljeno.
