# Generated by Django 5.1.7 on 2025-05-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backend", "0006_remove_studenttest_answers_alter_studenttest_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.studentanswer"
                    ),
                ),
                ("llm_response", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
