# Generated by Django 5.1.7 on 2025-07-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answergrade',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answergrade',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answergrade',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
