# Generated by Django 5.1.7 on 2025-07-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_studentanswer_test'),
        ('grading', '0002_remove_answergrade_is_correct_answergrade_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergrade',
            name='student_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='backend.studentanswer'),
        ),
    ]
