# Generated by Django 5.1.7 on 2025-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_answergrade_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answergrade',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
