stages:
  merge_inputs:
    foreach: ${datasets}
    do:
      cmd: python src/pipeline/01_merge_inputs.py --questions data/${item}/raw/questions.csv --answers data/${item}/raw/student_answers.csv --out data/${item}/interim/merged.csv
      deps:
        - src/pipeline/01_merge_inputs.py
        - data/${item}/raw/questions.csv
        - data/${item}/raw/student_answers.csv
      outs:
        - data/${item}/interim/merged.csv

  grade:
    foreach: ${datasets}
    do:
      cmd: python src/pipeline/02_grade.py --in data/${item}/interim/merged.csv --out data/${item}/graded --model ${params.models.model} --prompt_file ${params.prompts.professor_answer}
      deps:
        - src/pipeline/02_grade.py
        - data/${item}/interim/merged.csv
        - params.yaml
        - ${params.models.model}
        - ${params.prompts.professor_answer}
      outs:
        - data/${item}/graded
    
  # statistics:
  #   cmd: python src/pipeline/statistics.py --in ${data.root}/graded --out ${data.root}/stats
  #   deps:
  #     - src/pipeline/statistics.py
  #     - ${data.root}/graded
  #   outs:
  #     - ${data.root}/stats
