stages:
  merge_inputs:
    foreach: ${datasets}
    do:
      cmd: python src/pipeline/01_merge_inputs.py --questions data/${item}/raw/questions.csv --answers data/${item}/raw/student_answers.csv --out data/${item}/interim/merged.csv
      deps:
        - src/pipeline/01_merge_inputs.py
        - data/${item}/raw/questions.csv
        - data/${item}/raw/student_answers.csv
      outs:
        - data/${item}/interim/merged.csv
  grade_correct:
    foreach: ${datasets}
    do:
      cmd: python src/pipeline/02_grade_with_correct_answer.py --in data/${item}/interim/merged.csv --out data/${item}/graded/graded.${params.prompts.strictness}.${params.models.model}.correct.csv --model params/models/${params.models.model}.yaml --prompt_file params/prompts/strictness/${params.prompts.strictness}.yaml
      deps:
        - src/pipeline/02_grade_with_correct_answer.py
        - data/${item}/interim/merged.csv
        - params.yaml
        - params/models/${params.models.model}.yaml
        - params/prompts/strictness/${params.prompts.strictness}.yaml
      outs:
        - data/${item}/graded/graded.${params.prompts.strictness}.${params.models.model}.correct.csv

  # grade_textbook:
  #   foreach: ${datasets}
  #   do:
  #     cmd: python src/pipeline/03_grade_with_textbook.py --in data/${item}/interim/merged.csv --out data/${item}/graded/graded.${params.prompts.strictness}.${params.models.model}.textbook.csv --model params/models/${params.models.model}.yaml --prompt_file params/prompts/strictness/${params.prompts.strictness}.yaml
  #     deps:
  #       - src/pipeline/03_grade_with_textbook.py
  #       - data/${item}/interim/merged.csv
  #       - params.yaml
  #       - params/models/${params.models.model}.yaml
  #       - params/prompts/strictness/${params.prompts.strictness}.yaml
  #     outs:
  #       - data/${item}/graded/graded.${params.prompts.strictness}.${params.models.model}.textbook.csv

  # statistics:
  #   cmd: python src/pipeline/statistics.py --in ${data.root}/graded --out ${data.root}/stats
  #   deps:
  #     - src/pipeline/statistics.py
  #     - ${data.root}/graded
  #   outs:
  #     - ${data.root}/stats
